# Creating Server
version: '2'
services:
  registry:
      container_name: registry
      image: registry:latest
      restart: unless-stopped
      ports:
        - "5000:5000"
      environment:
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      volumes:
        - ${STORAGE}/docker-registry:/data
  jenkins: 
    container_name: jenkins
    build: jenkins/.
    privileged: true
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ${CONFIG}/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped
    depends_on:
      - gitea_db
    volumes:
      - ${CONFIG}/gitea:/data
      - ${STORAGE}/gitea:/git
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_TYPE=mysql
      - DB_HOST=gitea_db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
  gitea_db:
    container_name: gitea_db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ${CONFIG}/gitea_db:/var/lib/mysql
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
    volumes:
      - ${CONFIG}/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=bookstack
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - ${CONFIG}/bookstack_db:/config
    restart: unless-stopped
    
