# Creating Server
version: '2'
services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - 41742:41742
      - 41742:41742/udp
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANSMISSION_WEB_HOME=/combustion-release
    volumes:
      - ${CONFIG}/transmission:/config
      - ${STORAGE}/downloads/complete:/downloads
      - ${STORAGE}/downloads/temp:/var/lib/transmission-daemon/incomplete
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    ports:
      - "8989:8989"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${STORAGE}/series:/tv
      - ${STORAGE}/downloads/complete:/downloads
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    ports:
      - "7878:7878"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG}/radarr:/config
      - ${STORAGE}/movies:/movies
      - ${STORAGE}/downloads/complete:/downloads
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG}/jackett:/config
      - ${STORAGE}/downloads/blackhole:/downloads
  mylar:
    container_name: mylar
    build: https://github.com/Mathix/docker-mylar.git
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    ports:
      - "8090:8090"
    environment:
      - PUID=${PUID}
      - GUID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/mylar:/config
      - ${STORAGE}/downloads/complete:/downloads
      - ${STORAGE}/comics:/comics