# Creating Server
version: '3'
services:
  #transmission:
  #  container_name: transmission
  #  image: linuxserver/transmission
  #  restart: unless-stopped
  #  ports:
  #    - "9091:9091"
  #    - 41742:41742
  #    - 41742:41742/udp
  #  environment:
  #    - TZ=${TZ}
  #    - PUID=${PUID}
  #    - PGID=${PGID}
  #    - TRANSMISSION_WEB_HOME=/combustion-release
  #  volumes:
  #    - ${CONFIG}/transmission:/config
  #    - ${STORAGE}/downloads/complete:/downloads
  #    - ${STORAGE}/downloads/temp:/var/lib/transmission-daemon/incomplete

  transmission: 
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - "9091:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANSMISSION_WEB_HOME=/combustion-release
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_CONFIG=Canada
      - OPENVPN_USERNAME=dummy 
      - OPENVPN_PASSWORD=dummy
      - WEBPROXY_ENABLED=false 
      - LOCAL_NETWORK=10.0.0.0/16 
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
    volumes:
      - ${STORAGE}/downloads/complete:/downloads
      - ${CONFIG}/transmission-vpn:/data/transmission-home
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/transmission-vpn/:/etc/openvpn/custom/
          
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    ports:
      - "8989:8989"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${STORAGE}/series:/tv
      - ${STORAGE}/downloads/complete:/downloads
  radarr:
    container_name: radarr
    image: linuxserver/radarr:preview
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    ports:
      - "7878:7878"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG}/radarr:/config
      - ${STORAGE}/movies:/movies
      - ${STORAGE}/downloads/complete:/downloads
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG}/jackett:/config
      - ${STORAGE}/downloads/blackhole:/downloads
#  mylar:
#    container_name: mylar
#    build: https://github.com/Mathix/docker-mylar.git
#    restart: unless-stopped
#    depends_on:
#      - transmission
#      - jackett
#    ports:
#      - "8090:8090"
#    environment:
#      - PUID=${PUID}
#      - GUID=1000
#      - TZ=${TZ}
#    volumes:
#      - ${CONFIG}/mylar:/config
#      - ${STORAGE}/downloads/complete:/downloads
#      - ${STORAGE}/comics:/comics
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/lazylibrarian:/config
      - ${STORAGE}/downloads/complete:/downloads
      - ${STORAGE}/books:/books
      - ${STORAGE}/audio/audiobooks:/audiobooks
    ports:
      - 5299:5299
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    volumes:
      - ${CONFIG}/bazarr:/config
      - ${STORAGE}/movies:/movies
      - ${STORAGE}/series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - TZ=${TZ}

  unmanic-movies:
    image: josh5/unmanic:latest
    container_name: unmanic-movies
    volumes:
      - ${CONFIG}/unmanic:/config
      - ${STORAGE}/movies:/library
      - /tmp/unmanic:/tmp/unmanic
    ports:
      - 8801:8888
    restart: unless-stopped
    
  unmanic-tv:
    image: josh5/unmanic:latest
    container_name: unmanic-tv
    volumes:
      - ${CONFIG}/unmanic:/config
      - ${STORAGE}/series:/library
      - /tmp/unmanic:/tmp/unmanic
    ports:
      - 8802:8888
    restart: unless-stopped
    
