# Creating Server
version: '3.4'
services:    
   samba: 
      container_name: samba
      command: "-u \"${SAMBA_USERNAME};${SAMBA_PASSWORD}\" -s \"storage;/storage;yes;no;yes;all;none;;comment1\""
      ports:
        - "137:137/udp"
        - "138:138/udp"
        - "139:139/tcp"
        - "445:445/tcp"
      network_mode: host
      environment: 
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - "NMBD=True"
        - "RECYCLE=False"
        #- "USER=admin;admin;1001;admin"
      hostname: samba
      image: dperson/samba
      restart: always
      volumes: 
        - ${CONFIG}/samba:/etc/samba
        - ${STORAGE}:/storage