# Creating Server
version: '3'
services:
  mariadb:
    image: "linuxserver/mariadb"
    container_name: "mariadb"
    hostname: mariadb
    volumes:
        - ${CONFIG}/mariadb:/config
    #ports:
    #  - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      
  nextcloud:
    container_name: nextcloud
    restart: unless-stopped
    image: linuxserver/nextcloud
    depends_on:
      - mariadb
    volumes:
      - ${CONFIG}/nextcloud:/config
      - ${ROOT}/nextcloud:/data
      - ${STORAGE}:/server/data
      - ${CONFIG}:/server/config
    ports:
      - "443:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      
  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    links:
      - mariadb:db
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      
  samba: 
    container_name: samba
    command: "-u \"${SAMBA_USERNAME};${SAMBA_PASSWORD}\" -s \"storage;/storage;yes;no;yes;all;none;;comment1\" -s \"config;/config;yes;no;yes;all;none;;comment1\""
    hostname: samba
    image: dperson/samba
    restart: always
    volumes: 
      - ${CONFIG}/samba:/etc/samba
      - ${STORAGE}:/storage
      - ${CONFIG}:/config
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    network_mode: host
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - "NMBD=True"
      - "RECYCLE=False"
