# Creating Server
version: '3'
services:
  openvpn-home:
    image: linuxserver/openvpn-as
    container_name: openvpn-home
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- INTERFACE=eth0 #optional
    volumes:
      - ${CONFIG}/openvpn-home:/config
    ports:
      - 41739:943
      - 41740:41740
      - 41741:41741/udp
    restart: unless-stopped
  netdata:
    image: netdata/netdata
    hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
