# Creating Server
version: '2.4'
services:
  plex:
    container_name: plex
    hostname: media-server
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    runtime: nvidia
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "33400:33400"
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ${CONFIG}/plex:/config
      - ${CONFIG}/plex/transcode:/transcode
      - ${STORAGE}:/data
    devices:
     - /dev/dri:/dev/dri
    privileged: true
      
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli
    restart: unless-stopped
    depends_on: 
      - plex
    ports:
      - "8181:8181"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG}/tautulli:/config
      - ${CONFIG}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/plex_logs:ro

  ubooquity :
    container_name: ubooquity 
    image: linuxserver/ubooquity 
    restart: unless-stopped
    ports:
      - "2202:2202"
      - "2203:2203"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG}/ubooquity:/config
      - ${STORAGE}/comics:/comics
      - ${STORAGE}/books:/books     
    
  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    ports:
      - "3579:3579"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG}/ombi:/config
